exclude_patterns:
- "gen_*"
- "schema/*"
- "public/chartist/*"
- "public/trumbowyg/*"
- "public/jquery-emojiarea/*"
- "public/font-awesome-4.7.0/*"
- "public/jquery-3.1.1.min.js"
- "public/EQCSS.min.js"
- "public/EQCSS.js"
- "public/Sortable-1.4.0/*"