language: go
go:
  - "1.13"
  - "1.14"
  - master
before_install:
  - cd $HOME
  - git clone https://github.com/Azareal/Gosora gosora
  - cd gosora
  - chmod -R 0777 .
  - mv ./config/config_example.json ./config/config.json
  - ./update-deps-linux
  - ./dev-update-travis
  - mv ./experimental/plugin_sendmail.go ..
install: true
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script: ./run-linux-tests
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
addons:
  mariadb: '10.3'