env:
  global:
    - CC_TEST_REPORTER_ID=38ad11f95f28b1d33c9c31467f9eb5eb4e336e4e0e36046c86a4f7ff6e4c3977
language: go
go:
  - "1.10"
  - "1.11"
  - master
before_install:
  - cd $HOME
  - git clone https://github.com/Azareal/Gosora
  - cd Gosora
  - chmod -R 0777 .
  - mv ./config/config_example.json ./config/config.json
  - ./update-deps-linux
  - ./dev-update-travis
install: true
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script: ./run-linux-tests
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
addons:
  mariadb: '10.1'