version: "3"
services:
  web:
    build: .
    environment:
      - SERVER_PORT=8080
      - SECURE_SERVER_PORT=9090
      - SITE_NAME=${GOS_SITE_NAME:-Go.sora}
      - SITE_SHORT_NAME=${GOS_SHORT_SITE_NAME:-Gs}
      - SITE_URL=${GOS_SITE_URL}
      - MYSQL_DATABASE=${GOS_DBNAME:-gosora}
      - MYSQL_USER=${GOS_DBUSER:-gosora_user}
      - MYSQL_PASSWORD=${GOS_DBPASSWORD}
    volumes:
      - ./:/app
    ports:
      - "8080:80"
      - "9090:443"
    depends_on:
      - mariadb
  mariadb:
    environment:
      - MYSQL_ROOT_PASSWORD=${GOS_ROOT}
      - MYSQL_DATABASE=${GOS_DBNAME:-gosora}
      - MYSQL_USER=${GOS_DBUSER:-gosora_user}
      - MYSQL_PASSWORD=${GOS_DBPASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
    image: mariadb