// Generated by Gosora's Query Generator. DO NOT EDIT.
package main

var dbTablePrimaryKeys = map[string]string{
	"users":"uid",
	"users_groups":"gid",
	"users_groups_scheduler":"uid",
	"polls":"pollID",
	"registration_logs":"rlid",
	"activity_stream":"asid",
	"login_logs":"lid",
	"users_2fa_keys":"uid",
	"topics":"tid",
	"replies":"rid",
	"attachments":"attachID",
	"revisions":"reviseID",
	"users_avatar_queue":"uid",
	"forums":"fid",
	"menu_items":"miid",
	"users_replies":"rid",
	"word_filters":"wfid",
	"menus":"mid",
	"pages":"pid",
}
