// Generated by Gosora's Query Generator. DO NOT EDIT.
package main

var dbTablePrimaryKeys = map[string]string{
	"users":"uid",
	"topics":"tid",
	"revisions":"reviseID",
	"polls":"pollID",
	"users_replies":"rid",
	"activity_stream":"asid",
	"word_filters":"wfid",
	"users_groups":"gid",
	"users_groups_scheduler":"uid",
	"forums":"fid",
	"replies":"rid",
	"attachments":"attachID",
	"menus":"mid",
}
