// Code generated by Gosora. More below:
/* This file was automatically generated by the software. Please don't edit it as your changes may be overwritten at any moment. */
// +build !no_templategen
package main
import "io"
import "strconv"

func init() {
	template_profile_handle = template_profile
	//o_template_profile_handle = template_profile
	ctemplates = append(ctemplates,"profile")
	tmpl_ptr_map["profile"] = &template_profile_handle
	tmpl_ptr_map["o_profile"] = template_profile
}

func template_profile(tmpl_profile_vars ProfilePage, w io.Writer) {
w.Write(header_0)
w.Write([]byte(tmpl_profile_vars.Title))
w.Write(header_1)
if len(tmpl_profile_vars.Header.Stylesheets) != 0 {
for _, item := range tmpl_profile_vars.Header.Stylesheets {
w.Write(header_2)
w.Write([]byte(item))
w.Write(header_3)
}
}
w.Write(header_4)
if len(tmpl_profile_vars.Header.Scripts) != 0 {
for _, item := range tmpl_profile_vars.Header.Scripts {
w.Write(header_5)
w.Write([]byte(item))
w.Write(header_6)
}
}
w.Write(header_7)
w.Write([]byte(tmpl_profile_vars.CurrentUser.Session))
w.Write(header_8)
w.Write(menu_0)
if tmpl_profile_vars.CurrentUser.Loggedin {
w.Write(menu_1)
w.Write([]byte(tmpl_profile_vars.CurrentUser.Slug))
w.Write(menu_2)
w.Write([]byte(strconv.Itoa(tmpl_profile_vars.CurrentUser.ID)))
w.Write(menu_3)
if tmpl_profile_vars.CurrentUser.Is_Super_Mod {
w.Write(menu_4)
}
w.Write(menu_5)
w.Write([]byte(tmpl_profile_vars.CurrentUser.Session))
w.Write(menu_6)
} else {
w.Write(menu_7)
}
w.Write(menu_8)
w.Write(header_9)
if tmpl_profile_vars.Header.Widgets.RightSidebar != "" {
w.Write(header_10)
}
w.Write(header_11)
if len(tmpl_profile_vars.Header.NoticeList) != 0 {
for _, item := range tmpl_profile_vars.Header.NoticeList {
w.Write(header_12)
w.Write([]byte(item))
w.Write(header_13)
}
}
w.Write(profile_0)
w.Write([]byte(tmpl_profile_vars.ProfileOwner.Avatar))
w.Write(profile_1)
w.Write([]byte(tmpl_profile_vars.ProfileOwner.Name))
w.Write(profile_2)
if tmpl_profile_vars.ProfileOwner.Tag != "" {
w.Write(profile_3)
w.Write([]byte(tmpl_profile_vars.ProfileOwner.Tag))
w.Write(profile_4)
}
w.Write(profile_5)
if tmpl_profile_vars.CurrentUser.Is_Super_Mod && !tmpl_profile_vars.ProfileOwner.Is_Super_Mod {
w.Write(profile_6)
if tmpl_profile_vars.ProfileOwner.Is_Banned {
w.Write(profile_7)
w.Write([]byte(strconv.Itoa(tmpl_profile_vars.ProfileOwner.ID)))
w.Write(profile_8)
w.Write([]byte(tmpl_profile_vars.CurrentUser.Session))
w.Write(profile_9)
} else {
w.Write(profile_10)
w.Write([]byte(strconv.Itoa(tmpl_profile_vars.ProfileOwner.ID)))
w.Write(profile_11)
w.Write([]byte(tmpl_profile_vars.CurrentUser.Session))
w.Write(profile_12)
}
w.Write(profile_13)
}
w.Write(profile_14)
w.Write([]byte(strconv.Itoa(tmpl_profile_vars.ProfileOwner.ID)))
w.Write(profile_15)
w.Write([]byte(tmpl_profile_vars.CurrentUser.Session))
w.Write(profile_16)
if len(tmpl_profile_vars.ItemList) != 0 {
for _, item := range tmpl_profile_vars.ItemList {
w.Write(profile_17)
if item.Avatar != "" {
w.Write(profile_18)
w.Write([]byte(item.Avatar))
w.Write(profile_19)
if item.ContentLines <= 5 {
w.Write(profile_20)
}
w.Write(profile_21)
w.Write([]byte(string(item.Css)))
}
w.Write(profile_22)
w.Write([]byte(item.ContentHtml))
w.Write(profile_23)
w.Write([]byte(item.UserSlug))
w.Write(profile_24)
w.Write([]byte(strconv.Itoa(item.CreatedBy)))
w.Write(profile_25)
w.Write([]byte(item.CreatedByName))
w.Write(profile_26)
if tmpl_profile_vars.CurrentUser.Is_Mod {
w.Write(profile_27)
w.Write([]byte(strconv.Itoa(item.ID)))
w.Write(profile_28)
w.Write([]byte(strconv.Itoa(item.ID)))
w.Write(profile_29)
}
w.Write(profile_30)
w.Write([]byte(strconv.Itoa(item.ID)))
w.Write(profile_31)
w.Write([]byte(tmpl_profile_vars.CurrentUser.Session))
w.Write(profile_32)
if item.Tag != "" {
w.Write(profile_33)
w.Write([]byte(item.Tag))
w.Write(profile_34)
}
w.Write(profile_35)
}
}
w.Write(profile_36)
if !tmpl_profile_vars.CurrentUser.Is_Banned {
w.Write(profile_37)
w.Write([]byte(strconv.Itoa(tmpl_profile_vars.ProfileOwner.ID)))
w.Write(profile_38)
}
w.Write(profile_39)
w.Write(footer_0)
if tmpl_profile_vars.Header.Widgets.RightSidebar != "" {
w.Write(footer_1)
w.Write([]byte(string(tmpl_profile_vars.Header.Widgets.RightSidebar)))
w.Write(footer_2)
}
w.Write(footer_3)
}
