/* This file was automatically generated by the software. Please don't edit it as your changes may be overwritten at any moment. */
package main
import "strconv"
import "io"

func init() {
	template_forum_handle = template_forum
	//o_template_forum_handle = template_forum
	ctemplates = append(ctemplates,"forum")
	tmpl_ptr_map["forum"] = &template_forum_handle
	tmpl_ptr_map["o_forum"] = template_forum
}

func template_forum(tmpl_forum_vars ForumPage, w io.Writer) {
w.Write(header_0)
w.Write([]byte(tmpl_forum_vars.Title))
w.Write(header_1)
w.Write([]byte(tmpl_forum_vars.CurrentUser.Session))
w.Write(header_2)
w.Write(menu_0)
if tmpl_forum_vars.CurrentUser.Loggedin {
w.Write(menu_1)
w.Write([]byte(strconv.Itoa(tmpl_forum_vars.CurrentUser.ID)))
w.Write(menu_2)
if tmpl_forum_vars.CurrentUser.Is_Super_Mod {
w.Write(menu_3)
}
w.Write(menu_4)
w.Write([]byte(tmpl_forum_vars.CurrentUser.Session))
w.Write(menu_5)
} else {
w.Write(menu_6)
}
w.Write(menu_7)
w.Write(header_3)
if len(tmpl_forum_vars.NoticeList) != 0 {
for _, item := range tmpl_forum_vars.NoticeList {
w.Write(header_4)
w.Write([]byte(item))
w.Write(header_5)
}
}
if tmpl_forum_vars.Page > 1 {
w.Write(forum_0)
w.Write([]byte(strconv.Itoa(tmpl_forum_vars.Forum.ID)))
w.Write(forum_1)
w.Write([]byte(strconv.Itoa(tmpl_forum_vars.Page - 1)))
w.Write(forum_2)
}
if tmpl_forum_vars.LastPage != tmpl_forum_vars.Page {
w.Write(forum_3)
w.Write([]byte(strconv.Itoa(tmpl_forum_vars.Forum.ID)))
w.Write(forum_4)
w.Write([]byte(strconv.Itoa(tmpl_forum_vars.Page + 1)))
w.Write(forum_5)
w.Write([]byte(strconv.Itoa(tmpl_forum_vars.Forum.ID)))
w.Write(forum_6)
w.Write([]byte(strconv.Itoa(tmpl_forum_vars.Page + 1)))
w.Write(forum_7)
}
w.Write(forum_8)
w.Write([]byte(tmpl_forum_vars.Title))
w.Write(forum_9)
if len(tmpl_forum_vars.ItemList) != 0 {
for _, item := range tmpl_forum_vars.ItemList {
w.Write(forum_10)
if item.Avatar != "" {
w.Write(forum_11)
w.Write([]byte(item.Avatar))
w.Write(forum_12)
}
if item.Sticky {
w.Write(forum_13)
} else {
if item.Is_Closed {
w.Write(forum_14)
}
}
w.Write(forum_15)
w.Write([]byte(strconv.Itoa(item.ID)))
w.Write(forum_16)
w.Write([]byte(item.Title))
w.Write(forum_17)
if item.Is_Closed {
w.Write(forum_18)
}
w.Write(forum_19)
}
} else {
w.Write(forum_20)
}
w.Write(forum_21)
w.Write(footer_0)
}
