// +build !no_templategen

// Code generated by Gosora. More below:
/* This file was automatically generated by the software. Please don't edit it as your changes may be overwritten at any moment. */
package main
import "net/http"
import "./common"

var ip_search_Tmpl_Phrase_ID int

// nolint
func init() {
	common.Template_ip_search_handle = Template_ip_search
	common.Ctemplates = append(common.Ctemplates,"ip_search")
	common.TmplPtrMap["ip_search"] = &common.Template_ip_search_handle
	common.TmplPtrMap["o_ip_search"] = Template_ip_search
	ip_search_Tmpl_Phrase_ID = common.RegisterTmplPhraseNames([]string{
		"ip_search_head",
		"ip_search_no_users",
	})
}

// nolint
func Template_ip_search(tmpl_ip_search_vars common.IPSearchPage, w http.ResponseWriter) error {
	var phrases = common.GetTmplPhrasesBytes(ip_search_Tmpl_Phrase_ID)
w.Write(header_0)
w.Write([]byte(tmpl_ip_search_vars.Title))
w.Write(header_1)
w.Write([]byte(tmpl_ip_search_vars.Header.Site.Name))
w.Write(header_2)
w.Write([]byte(tmpl_ip_search_vars.Header.Theme.Name))
w.Write(header_3)
if len(tmpl_ip_search_vars.Header.Stylesheets) != 0 {
for _, item := range tmpl_ip_search_vars.Header.Stylesheets {
w.Write(header_4)
w.Write([]byte(item))
w.Write(header_5)
}
}
w.Write(header_6)
if len(tmpl_ip_search_vars.Header.Scripts) != 0 {
for _, item := range tmpl_ip_search_vars.Header.Scripts {
w.Write(header_7)
w.Write([]byte(item))
w.Write(header_8)
}
}
w.Write(header_9)
w.Write([]byte(tmpl_ip_search_vars.CurrentUser.Session))
w.Write(header_10)
w.Write([]byte(tmpl_ip_search_vars.Header.Site.URL))
w.Write(header_11)
if tmpl_ip_search_vars.Header.MetaDesc != "" {
w.Write(header_12)
w.Write([]byte(tmpl_ip_search_vars.Header.MetaDesc))
w.Write(header_13)
}
w.Write(header_14)
if !tmpl_ip_search_vars.CurrentUser.IsSuperMod {
w.Write(header_15)
}
w.Write(header_16)
w.Write(menu_0)
w.Write(menu_1)
w.Write([]byte(tmpl_ip_search_vars.Header.Site.ShortName))
w.Write(menu_2)
if tmpl_ip_search_vars.CurrentUser.Loggedin {
w.Write(menu_3)
w.Write([]byte(tmpl_ip_search_vars.CurrentUser.Link))
w.Write(menu_4)
w.Write([]byte(tmpl_ip_search_vars.CurrentUser.Session))
w.Write(menu_5)
} else {
w.Write(menu_6)
}
w.Write(menu_7)
w.Write(header_17)
if tmpl_ip_search_vars.Header.Widgets.RightSidebar != "" {
w.Write(header_18)
}
w.Write(header_19)
if len(tmpl_ip_search_vars.Header.NoticeList) != 0 {
for _, item := range tmpl_ip_search_vars.Header.NoticeList {
w.Write(header_20)
w.Write([]byte(item))
w.Write(header_21)
}
}
w.Write(ip_search_0)
w.Write(phrases[0])
w.Write(ip_search_1)
if tmpl_ip_search_vars.IP != "" {
w.Write(ip_search_2)
w.Write([]byte(tmpl_ip_search_vars.IP))
w.Write(ip_search_3)
}
w.Write(ip_search_4)
if tmpl_ip_search_vars.IP != "" {
w.Write(ip_search_5)
if len(tmpl_ip_search_vars.ItemList) != 0 {
for _, item := range tmpl_ip_search_vars.ItemList {
w.Write(ip_search_6)
w.Write([]byte(item.Avatar))
w.Write(ip_search_7)
w.Write([]byte(item.Avatar))
w.Write(ip_search_8)
w.Write([]byte(item.Name))
w.Write(ip_search_9)
w.Write([]byte(item.Link))
w.Write(ip_search_10)
w.Write([]byte(item.Name))
w.Write(ip_search_11)
}
} else {
w.Write(ip_search_12)
w.Write(phrases[1])
w.Write(ip_search_13)
}

w.Write(ip_search_14)
}
w.Write(ip_search_15)
w.Write(footer_0)
w.Write([]byte(common.BuildWidget("footer",tmpl_ip_search_vars.Header)))
w.Write(footer_1)
if len(tmpl_ip_search_vars.Header.Themes) != 0 {
for _, item := range tmpl_ip_search_vars.Header.Themes {
if !item.HideFromThemes {
w.Write(footer_2)
w.Write([]byte(item.Name))
w.Write(footer_3)
if tmpl_ip_search_vars.Header.Theme.Name == item.Name {
w.Write(footer_4)
}
w.Write(footer_5)
w.Write([]byte(item.FriendlyName))
w.Write(footer_6)
}
}
}
w.Write(footer_7)
w.Write([]byte(common.BuildWidget("rightSidebar",tmpl_ip_search_vars.Header)))
w.Write(footer_8)
	return nil
}
