// +build !no_templategen

// Code generated by Gosora. More below:
/* This file was automatically generated by the software. Please don't edit it as your changes may be overwritten at any moment. */
package main
import "net/http"
import "./common"
import "strconv"

var forum_Tmpl_Phrase_ID int

// nolint
func init() {
	common.Template_forum_handle = Template_forum
	common.Ctemplates = append(common.Ctemplates,"forum")
	common.TmplPtrMap["forum"] = &common.Template_forum_handle
	common.TmplPtrMap["o_forum"] = Template_forum
	forum_Tmpl_Phrase_ID = common.RegisterTmplPhraseNames([]string{
		"menu_forums_aria",
		"menu_forums_tooltip",
		"menu_topics_aria",
		"menu_topics_tooltip",
		"menu_alert_counter_aria",
		"menu_alert_list_aria",
		"menu_account_aria",
		"menu_account_tooltip",
		"menu_profile_aria",
		"menu_profile_tooltip",
		"menu_panel_aria",
		"menu_panel_tooltip",
		"menu_logout_aria",
		"menu_logout_tooltip",
		"menu_register_aria",
		"menu_register_tooltip",
		"menu_login_aria",
		"menu_login_tooltip",
		"menu_hamburger_tooltip",
		"paginator_prev_page_aria",
		"paginator_less_than",
		"paginator_next_page_aria",
		"paginator_greater_than",
		"topic_list_create_topic_tooltip",
		"topic_list_create_topic_aria",
		"topic_list_moderate_tooltip",
		"topic_list_moderate_aria",
		"forum_locked_tooltip",
		"forum_locked_aria",
		"topic_list_what_to_do",
		"topic_list_moderate_delete",
		"topic_list_moderate_lock",
		"topic_list_moderate_move",
		"topic_list_moderate_run",
		"quick_topic_aria",
		"quick_topic_avatar_alt",
		"quick_topic_avatar_tooltip",
		"quick_topic_whatsup",
		"quick_topic_content_placeholder",
		"quick_topic_create_topic_button",
		"quick_topic_add_poll_button",
		"quick_topic_add_file_button",
		"quick_topic_cancel_button",
		"forum_list_aria",
		"status_closed_tooltip",
		"status_pinned_tooltip",
		"forum_no_topics",
		"forum_start_one",
		"paginator_prev_page_aria",
		"paginator_prev_page",
		"paginator_next_page_aria",
		"paginator_next_page",
		"footer_powered_by",
		"footer_made_with_love",
		"footer_theme_selector_aria",
	})
}

// nolint
func Template_forum(tmpl_forum_vars common.ForumPage, w http.ResponseWriter) error {
	var phrases = common.GetTmplPhrasesBytes(forum_Tmpl_Phrase_ID)
w.Write(header_0)
w.Write([]byte(tmpl_forum_vars.Title))
w.Write(header_1)
w.Write([]byte(tmpl_forum_vars.Header.Site.Name))
w.Write(header_2)
w.Write([]byte(tmpl_forum_vars.Header.Theme.Name))
w.Write(header_3)
if len(tmpl_forum_vars.Header.Stylesheets) != 0 {
for _, item := range tmpl_forum_vars.Header.Stylesheets {
w.Write(header_4)
w.Write([]byte(item))
w.Write(header_5)
}
}
w.Write(header_6)
if len(tmpl_forum_vars.Header.Scripts) != 0 {
for _, item := range tmpl_forum_vars.Header.Scripts {
w.Write(header_7)
w.Write([]byte(item))
w.Write(header_8)
}
}
w.Write(header_9)
w.Write([]byte(tmpl_forum_vars.CurrentUser.Session))
w.Write(header_10)
w.Write([]byte(tmpl_forum_vars.Header.Site.URL))
w.Write(header_11)
if tmpl_forum_vars.Header.MetaDesc != "" {
w.Write(header_12)
w.Write([]byte(tmpl_forum_vars.Header.MetaDesc))
w.Write(header_13)
}
w.Write(header_14)
if !tmpl_forum_vars.CurrentUser.IsSuperMod {
w.Write(header_15)
}
w.Write(header_16)
w.Write(menu_0)
w.Write(menu_1)
w.Write([]byte(tmpl_forum_vars.Header.Site.ShortName))
w.Write(menu_2)
w.Write(phrases[0])
w.Write(menu_3)
w.Write(phrases[1])
w.Write(menu_4)
w.Write(phrases[2])
w.Write(menu_5)
w.Write(phrases[3])
w.Write(menu_6)
w.Write(phrases[4])
w.Write(menu_7)
w.Write(phrases[5])
w.Write(menu_8)
if tmpl_forum_vars.CurrentUser.Loggedin {
w.Write(menu_9)
w.Write(phrases[6])
w.Write(menu_10)
w.Write(phrases[7])
w.Write(menu_11)
w.Write([]byte(tmpl_forum_vars.CurrentUser.Link))
w.Write(menu_12)
w.Write(phrases[8])
w.Write(menu_13)
w.Write(phrases[9])
w.Write(menu_14)
w.Write(phrases[10])
w.Write(menu_15)
w.Write(phrases[11])
w.Write(menu_16)
w.Write([]byte(tmpl_forum_vars.CurrentUser.Session))
w.Write(menu_17)
w.Write(phrases[12])
w.Write(menu_18)
w.Write(phrases[13])
w.Write(menu_19)
} else {
w.Write(menu_20)
w.Write(phrases[14])
w.Write(menu_21)
w.Write(phrases[15])
w.Write(menu_22)
w.Write(phrases[16])
w.Write(menu_23)
w.Write(phrases[17])
w.Write(menu_24)
}
w.Write(menu_25)
w.Write(phrases[18])
w.Write(menu_26)
w.Write(header_17)
if tmpl_forum_vars.Header.Widgets.RightSidebar != "" {
w.Write(header_18)
}
w.Write(header_19)
if len(tmpl_forum_vars.Header.NoticeList) != 0 {
for _, item := range tmpl_forum_vars.Header.NoticeList {
w.Write(header_20)
w.Write([]byte(item))
w.Write(header_21)
}
}
w.Write(header_22)
if tmpl_forum_vars.Page > 1 {
w.Write(forum_0)
w.Write(phrases[19])
w.Write(forum_1)
w.Write([]byte(strconv.Itoa(tmpl_forum_vars.Forum.ID)))
w.Write(forum_2)
w.Write([]byte(strconv.Itoa(tmpl_forum_vars.Page - 1)))
w.Write(forum_3)
w.Write(phrases[20])
w.Write(forum_4)
}
if tmpl_forum_vars.LastPage != tmpl_forum_vars.Page {
w.Write(forum_5)
w.Write(phrases[21])
w.Write(forum_6)
w.Write([]byte(strconv.Itoa(tmpl_forum_vars.Forum.ID)))
w.Write(forum_7)
w.Write([]byte(strconv.Itoa(tmpl_forum_vars.Page + 1)))
w.Write(forum_8)
w.Write(phrases[22])
w.Write(forum_9)
}
w.Write(forum_10)
if tmpl_forum_vars.CurrentUser.ID != 0 {
w.Write(forum_11)
}
w.Write(forum_12)
w.Write([]byte(tmpl_forum_vars.Title))
w.Write(forum_13)
if tmpl_forum_vars.CurrentUser.ID != 0 {
w.Write(forum_14)
if tmpl_forum_vars.CurrentUser.Perms.CreateTopic {
w.Write(forum_15)
w.Write(phrases[23])
w.Write(forum_16)
w.Write(phrases[24])
w.Write(forum_17)
w.Write([]byte(strconv.Itoa(tmpl_forum_vars.Forum.ID)))
w.Write(forum_18)
w.Write(forum_19)
w.Write(phrases[25])
w.Write(forum_20)
w.Write(phrases[26])
w.Write(forum_21)
} else {
w.Write(forum_22)
w.Write(phrases[27])
w.Write(forum_23)
w.Write(phrases[28])
w.Write(forum_24)
}
w.Write(forum_25)
}
w.Write(forum_26)
if tmpl_forum_vars.CurrentUser.ID != 0 {
w.Write(forum_27)
w.Write(phrases[29])
w.Write(forum_28)
w.Write(phrases[30])
w.Write(forum_29)
w.Write(phrases[31])
w.Write(forum_30)
w.Write(phrases[32])
w.Write(forum_31)
w.Write(phrases[33])
w.Write(forum_32)
if tmpl_forum_vars.CurrentUser.Perms.CreateTopic {
w.Write(forum_33)
w.Write(phrases[34])
w.Write(forum_34)
w.Write([]byte(tmpl_forum_vars.CurrentUser.Avatar))
w.Write(forum_35)
w.Write(phrases[35])
w.Write(forum_36)
w.Write(phrases[36])
w.Write(forum_37)
w.Write([]byte(strconv.Itoa(tmpl_forum_vars.Forum.ID)))
w.Write(forum_38)
w.Write(phrases[37])
w.Write(forum_39)
w.Write(phrases[38])
w.Write(forum_40)
w.Write(phrases[39])
w.Write(forum_41)
w.Write(phrases[40])
w.Write(forum_42)
if tmpl_forum_vars.CurrentUser.Perms.UploadFiles {
w.Write(forum_43)
w.Write(phrases[41])
w.Write(forum_44)
}
w.Write(forum_45)
w.Write(phrases[42])
w.Write(forum_46)
}
}
w.Write(forum_47)
w.Write(phrases[43])
w.Write(forum_48)
if len(tmpl_forum_vars.ItemList) != 0 {
for _, item := range tmpl_forum_vars.ItemList {
w.Write(forum_49)
w.Write([]byte(strconv.Itoa(item.ID)))
w.Write(forum_50)
if item.Sticky {
w.Write(forum_51)
} else {
if item.IsClosed {
w.Write(forum_52)
}
}
w.Write(forum_53)
w.Write([]byte(item.Creator.Link))
w.Write(forum_54)
w.Write([]byte(item.Creator.Avatar))
w.Write(forum_55)
w.Write([]byte(item.Creator.Name))
w.Write(forum_56)
w.Write([]byte(item.Creator.Name))
w.Write(forum_57)
w.Write([]byte(item.Link))
w.Write(forum_58)
w.Write([]byte(item.Title))
w.Write(forum_59)
w.Write([]byte(item.Creator.Link))
w.Write(forum_60)
w.Write([]byte(item.Creator.Name))
w.Write(forum_61)
if item.IsClosed {
w.Write(forum_62)
w.Write(phrases[44])
w.Write(forum_63)
}
if item.Sticky {
w.Write(forum_64)
w.Write(phrases[45])
w.Write(forum_65)
}
w.Write(forum_66)
w.Write([]byte(strconv.Itoa(item.PostCount)))
w.Write(forum_67)
w.Write([]byte(strconv.Itoa(item.LikeCount)))
w.Write(forum_68)
if item.Sticky {
w.Write(forum_69)
} else {
if item.IsClosed {
w.Write(forum_70)
}
}
w.Write(forum_71)
w.Write([]byte(item.LastUser.Link))
w.Write(forum_72)
w.Write([]byte(item.LastUser.Avatar))
w.Write(forum_73)
w.Write([]byte(item.LastUser.Name))
w.Write(forum_74)
w.Write([]byte(item.LastUser.Name))
w.Write(forum_75)
w.Write([]byte(item.LastUser.Link))
w.Write(forum_76)
w.Write([]byte(item.LastUser.Name))
w.Write(forum_77)
w.Write([]byte(item.RelativeLastReplyAt))
w.Write(forum_78)
}
} else {
w.Write(forum_79)
w.Write(phrases[46])
if tmpl_forum_vars.CurrentUser.Perms.CreateTopic {
w.Write(forum_80)
w.Write([]byte(strconv.Itoa(tmpl_forum_vars.Forum.ID)))
w.Write(forum_81)
w.Write(phrases[47])
w.Write(forum_82)
}
w.Write(forum_83)
}
w.Write(forum_84)
if tmpl_forum_vars.LastPage > 1 {
w.Write(paginator_0)
if tmpl_forum_vars.Page > 1 {
w.Write(paginator_1)
w.Write([]byte(strconv.Itoa(tmpl_forum_vars.Page - 1)))
w.Write(paginator_2)
w.Write(phrases[48])
w.Write(paginator_3)
w.Write(phrases[49])
w.Write(paginator_4)
w.Write([]byte(strconv.Itoa(tmpl_forum_vars.Page - 1)))
w.Write(paginator_5)
}
if len(tmpl_forum_vars.PageList) != 0 {
for _, item := range tmpl_forum_vars.PageList {
w.Write(paginator_6)
w.Write([]byte(strconv.Itoa(item)))
w.Write(paginator_7)
w.Write([]byte(strconv.Itoa(item)))
w.Write(paginator_8)
}
}
if tmpl_forum_vars.LastPage != tmpl_forum_vars.Page {
w.Write(paginator_9)
w.Write([]byte(strconv.Itoa(tmpl_forum_vars.Page + 1)))
w.Write(paginator_10)
w.Write([]byte(strconv.Itoa(tmpl_forum_vars.Page + 1)))
w.Write(paginator_11)
w.Write(phrases[50])
w.Write(paginator_12)
w.Write(phrases[51])
w.Write(paginator_13)
}
w.Write(paginator_14)
}
w.Write(forum_85)
w.Write(footer_0)
w.Write([]byte(common.BuildWidget("footer",tmpl_forum_vars.Header)))
w.Write(footer_1)
w.Write(phrases[52])
w.Write(footer_2)
w.Write(phrases[53])
w.Write(footer_3)
w.Write(phrases[54])
w.Write(footer_4)
if len(tmpl_forum_vars.Header.Themes) != 0 {
for _, item := range tmpl_forum_vars.Header.Themes {
if !item.HideFromThemes {
w.Write(footer_5)
w.Write([]byte(item.Name))
w.Write(footer_6)
if tmpl_forum_vars.Header.Theme.Name == item.Name {
w.Write(footer_7)
}
w.Write(footer_8)
w.Write([]byte(item.FriendlyName))
w.Write(footer_9)
}
}
}
w.Write(footer_10)
w.Write([]byte(common.BuildWidget("rightSidebar",tmpl_forum_vars.Header)))
w.Write(footer_11)
	return nil
}
